version: "3.8"

services:

  api-gateway:
    image: nginx:alpine
    volumes:
      - ./src/api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - http-endpoint
      - message-broker
    ports:
      - "7000:80"

  http-endpoint:
    image: everything-messages/http-endpoint:latest
    build:
      context: ./src
      dockerfile: ./Api/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    scale: 2 # just so we have multiple
    depends_on:
      - message-broker
      - document-store

  worker-endpoint:
    image: everything-messages/worker-endpoint:latest
    build:
      context: ./src
      dockerfile: ./BackgroundWorkers/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    scale: 2 # just so we have multiple
    depends_on:
      - message-broker
      - document-store

  auditing-endpoint:
    image: everything-messages/auditing-endpoint:latest
    build:
      context: ./src
      dockerfile: ./BackgroundAuditor/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    scale: 5 # just so we have multiple
    depends_on:
      - message-broker
      - document-store

  message-broker:
    image: rabbitmq:3.8.17-management-alpine
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 10
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  document-store:
    image: mongo:4.4.6
    ports:
      - "27017-27019:27017-27019"

