version: "3.8"

services:

  api:
    image: everything-messages/api-gateway
    build:
      context: ./src
      dockerfile: ./Api/Dockerfile
    restart: always
    # ports:
    #  - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    scale: 2 # just so we hit different machines :D

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"

  api-gateway:
    image: nginx:alpine
    volumes:
      - ./src/api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - rabbitmq
    ports:
      - "7000:80"
